### PR TITLE
DOC: give a link for kubelet

### PR DESCRIPTION
**Pull request by MalloZup**
Is useful for newbies :sunflower: 

You can see it [here](https://github.com/MalloZup/caasp-devenv/tree/kubelet-link#caasp-development-environment)

The link is from upstream so we can consider it stable.

### CODE REVIEW

**Comment by ereslibre** [comment]
Hello @MalloZup. Thank you for your PR. This project is unmaintained and to be removed. All use cases should be covered by github.com/kubic-project/automation using the `caasp-devenv` script that you can find there.

**Comment by MalloZup** [comment]
@ereslibre ok thank you. I think then that the solution here, is to put the `unmaintained status` somewhere in the first line of the README.md of this project and reference to the automation project.

Feel free to close this pr then.

Thank you for info

**Comment by MalloZup** [comment]
@flavio @ereslibre   could you please make a remark on the readme.md that the projec is unmaintained? thx

**Comment by ereslibre** [comment]
@MalloZup I have already created a PR for that: https://github.com/kubic-project/caasp-devenv/pull/41

Thank you.

**Pull request closed without merging**
