### PR TITLE
Don't hide PKI Generation output

### PR DESCRIPTION
**Pull request by kiall**

### CODE REVIEW

**Comment by mssola** [comment]
@kiall is Jenkins reliable ? It's failing on a Salt highstate, but it's unrelated to this change ...

**Comment by ereslibre** [comment]
@kiall We want to be verbose here? The generation process should be stable... do we want to be verbose here? Was this trying to track down our CI problems?

**Comment by kiall** [comment]
@ereslibre it was trying to track down the CI issues, specifically the empty ca.crt file you also noticed earlier ;)

@mssola jenkins was hit by the same issue as concourse, the job cache caused some issues. I've retriggered the job (and without a `git push -f` ;))

**Comment by kiall** [comment]
@ereslibre re "We want to be verbose here?" given it's about to start spewing Kubelet logs right after, I don't see much harm in letting this be shown.. And if it saves a debugging a CI fail we suspect is TLS related, which turns out to be something else, even better :)

**Comment by ereslibre** [comment]
> given it's about to start spewing Kubelet logs right after

Absolutely :+1:

**Pull request merged**
