### PR TITLE
Add several salt helper scripts

### PR DESCRIPTION
**Pull request by kiall**
I'm constantly typoing these, or using `salt '*'` in place of `salt-run`, so I've just added some scripts for the common calls I make against my dev environment.

### CODE REVIEW

**Comment by mssola** [comment]
Would it make sense to have a single file, with subcommands ? Just to avoid adding a new file for each possible command 😃

**Comment by kiall** [comment]
I wanted to avoid going down the whole argument parsing route, where different subcommands need different arguments etc for simplicity :)

i.e. figure out what all the common stuff people do is, then figure out how to wrap it something cleaner than separate one off scripts!

**Comment by mssola** [comment]
I see. Makes sense. Maybe inside of a `scripts` directory then ?

**Comment by kiall** [comment]
Yea, a scripts dir makes sense - moved

**Pull request merged**
