### PR TITLE
Process annotations also

### PR DESCRIPTION
**Pull request by robdaemon**
Updates process_manifest.rb to update the image tags, volumes and
environment variables of init-container entries in the pod annotations
section.

### CODE REVIEW

**Comment by robdaemon** [comment]
I'll change the quotes to double quotes - one sec

**Comment by robdaemon** [comment]
okay, commit amended :)

**Comment by ereslibre** [comment]
Okay, let me give it a fast run. I am now confused: if the annotation is a string in YAML, when do we `JSON.parse` it? Can we call `patch_container` directly there? I mean, we didn't really parse the JSON, right?

**Comment by robdaemon** [comment]
So, YAML is a superset of JSON, so a YAML parser can parse any JSON. So, I'm parsing the annotation entry in line 37, then iterating through it and treating it like any other `container` element.

I write it back out as JSON because embedding YAML inside YAML doesn't seem to work.

**Comment by ereslibre** [comment]
I didn't know YAML is a formal superset of JSON. Holy cow.

**Comment by robdaemon** [comment]
Yeah that one was kind of mind boggling to me when I learned it :smile:

**Pull request merged**
